### ISSUE TITLE
Atributo alt en imagenes

### ISSUE THREAD

**Issue by castromaciel** [GermanKreibohmAcotto/ProyectoFinalRollingCode#17]
## Proceso

1. Navegación en página de inicio.
2. Seleccionar el botón de ver más en los productos.
3. Inspeccionar las imágenes del inicio, productos y logo.

## Resultado esperado

Se esperaba que toda imagen tenga su respectivo texto alternativo, por lo tanto se genera una mala experiencia para los usuarios.

## Resultado actual

Actualmente las imágenes no poseen un tento alternativo, a excepción de las que se presentan en el footer.

## Captura

![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/1797d664-9697-4df8-93b9-5a1c32ba4875)

![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/4b0e3a03-148b-47c2-94d9-9223f377cf71)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by TomasBach** [comment]
## Atributo alt en imagenes 

### Causa
Las imágenes no poseian un tento alternativo, a excepción de las que se presentan en el footer.

### Solucion
Con la funcion de buscar de VSC buscamos el termino alt="" y de a uno los reemplazamos con el texto correspondiente 

### Evidencia
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/137799623/62824145-9abd-48e6-8c04-e398e7dbae8d)


### Commit
a01ea58 y 351fb4f
