### ISSUE TITLE
Logo en el footer

### ISSUE THREAD

**Issue by castromaciel** [GermanKreibohmAcotto/ProyectoFinalRollingCode#18]
## Proceso

1. Navegar hacía el footer.
2. Click al logo representativo de la web.

## Resultado esperado

Se esperaba que al darle click al logo, este redirija al usuario hasta la página de inicio.

## Resultado actual

Actualmente al intentar clickearlo no cumple ninguna función.

## Captura

![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/7ce9dc44-fc4d-43a2-a980-5e5a5da4b18c)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by TomasBach** [comment]
## Logo en el footer

### Causa
Al intentar clickearlo no cumple ninguna función.

### Solucion
Se localizo la imagen y se le asigno redireccion hacia el inicio del homepage

### Evidencia
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/137799623/1d1c7992-0921-4e91-ba6f-9b00e597a6c8)

### Commit
2f71773
