### ISSUE TITLE
Administración

### ISSUE THREAD

**Issue by castromaciel** [GermanKreibohmAcotto/ProyectoFinalRollingCode#19]
## Proceso

1. Iniciar sesión como Admin.

## Resultado esperado

Se esperaba que al iniciar sesión se presente ensección de usuarios o productos.

## Resultado actual

Actualmente al iniciar sesión como administrador, el primer pantallazo es el inicio, pero este no tiene una buena interfaz de usuario.

## Captura
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/bfacac2c-88b9-439e-8427-7bfafbd991be)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by TomasBach** [comment]
## Administración 

### Causa
Al iniciar sesión como administrador, el primer pantallazo es el inicio, pero este no tiene una buena interfaz de usuario.

### Solucion
Se elimino el inicio de vista de administrador y se modifico la redireccion hacia la vista de usuarios

### Evidencia
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/137799623/77579cf0-cbe0-4dfe-aed4-8b03c1399911)

### Commit
83ab269
