### ISSUE TITLE
Console logs

### ISSUE THREAD

**Issue by castromaciel** [GermanKreibohmAcotto/ProyectoFinalRollingCode#20]
Actualmente tanto en administración como en usuarios se generan errores y se presentan en consola.

Inicio de sesión y registrar usuarios:
-Crear un usuario existente.
-Ingresar con un erróneamente

Como usuario:
-Buscar productos
-Añadir productos al carrito.
-Añadir a favoritos.
-Enviar formulario de contactos.
-Dirigirse a la sección de favoritos.
-Dirigirse a la sección de carrito.

Como administrador:
-Editar y borrar un usuario.
-Editar, borrar y crear productos.
-Sección imágenes e intentar subir una.

## Captura
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/9b3caf92-220e-4b28-8bda-6125c4ba7f0d)
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/1ed582fa-d456-44a5-8f9b-f11a176ba639)

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by TomasBach** [comment]
## Administración 

### Causa
Tanto en administración como en usuarios se generan errores y se presentan en consola.

### Solucion
Con la funcion de buscar de VSC buscamos el termino console.log y de a uno los reemplazamos con un swal o similar

### Evidencia
![image](https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/137799623/ed632276-6c51-4997-8910-587a35ec462d)

### Commit
57424cc
