### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by castromaciel** [GermanKreibohmAcotto/ProyectoFinalRollingCode#21]
## Proceso

1. Dar click en el enlace iniciar sesión
2. Completar el formulario
3. Dar click varias veces en el boton de iniciar sesión

## Resultado esperado

No se debería permitir iniciar sesión 2 veces o mas. Al dar click en login, se debería presentar un spinner indicando al usuario que se está realizando una acción.

## Resultado actual

Actualmente permite dar click mas de una vez al iniciar sesión

## Captura

https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/f36a6638-bd33-4dbf-9854-31d584dbdb1d

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by GermanKreibohmAcotto** [comment]
# Inicio de Sesión

## Causa
Se podia apretar mas de una vez el boton de iniciar sesion causando que se ejecute varias veces el SweetAlert.
## Solucion
Creamos un useState para poder manejar la propiedad disabled del boton. lo puse en el onClick del boton para que cuando este funcione lo ponga en true al disabled para que el boton no se pueda pulsar. y luego lo puse para que se ponga el disabled en false para que este se vuelva activar para que en el momento de volver a iniciar sesion este activado el boton.
## Commit
6f3f4aa
