### ISSUE TITLE
Redirecciones - Error Vercel

### ISSUE THREAD

**Issue by castromaciel** [GermanKreibohmAcotto/ProyectoFinalRollingCode#22]
## Proceso

1. Dirigirse a alguna ruta de la página
2. Recargar la página

## Resultado esperado

Se espera que al recargar la pagina, la información se refresque sin generar inconvenientes.

## Resultado actual

Al recargar la página en una ruta, da un error en vercel.

## Captura

https://github.com/GermanKreibohmAcotto/ProyectoFinalRollingCode/assets/83432755/0be2863f-f30b-4f7e-a836-f6b3447686df

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by GermanKreibohmAcotto** [comment]
# Error Vercel

## Causa

Daba un error vercel al recargar la pagina en cualquiera de las secciones menos la pagina index.

## Solucion
Agregar el siguiente codigo al archivo vercel.json y agregarlo al FrontEnd

    { "rewrites": [ { "source": "/(.*)", "destination": "/" } ] }
## Commit
659b384
